### ISSUE TITLE
[21-12-07] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#16]
블로그 포스팅 이후 주소 댓글 남겨주세요

- [x] 파이썬 공부

- [x] 파이썬 블로그 포스팅 

- [x] 정보처리기사 복습

- [x] AI 모듈에 관해 찾아보기

- [x] 기획서 수정해서 이동휘교수님께 보내기
