### ISSUE TITLE
[21-12-09] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#26]
- [ ] 정보처리기사 실기 개념 2강

- [ ] 스위프트 공부 

- [ ] 스위프트 관련 블로그 포스팅 후 댓글

- [ ] 스위프트 인강 15회 분으로 나누어서 계획 짜서 알려주세요

**Comment by park121234** [comment]
11강 원피스 현상금업그레이드(1)
12강 애플뮤직st 음악앱 (2)
13강 todo리스트 앱 (2)
14강 네트워킹 (1)
15강 넷플릭스st 영상앱 (1)
16강 Firevase (1)
17강 넷플릭스st 확장앱 (1)
18강 FullScreen 카매라앱 (2)
19강 CoreML 개와 강아지분류기(1)

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260
