### ISSUE TITLE
[21-12-09] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#27]
- [ ] 정보처리기사 실기 개념 2강

- [ ] 리엑트 공부 

- [ ] 리엑트 관련 블로그 포스팅 후 댓글

- [ ] 리엑트 인강 15회 분으로 나누어서 계획 짜서 알려주세요

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222591483218

1. 1장 {33강 ~ 36강}
2. 2장 {00강 ~ 05강}
3. 2장 {06강 ~ 13강}
4. 3장 {00강 ~ 04강}
5. 4장 {00강 ~ 03강}
6. 4장 {04강 ~ 07강}
7. 5장 {00강 ~ 07강}
8. 6장 {00강 ~ 06강}
9. 6장 {07강 ~ 14강}
10. 7장 {00강 ~ 10강}
11. 7장 {11강 ~ 16강}
12. 7장 {17강 ~ 22강}
13. 8장 {00강 ~ 07강}
14. 8장 {08강 ~ 11강}
15. 8장 {12강 ~ 18강}
