### ISSUE TITLE
[21-12-09] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#28]
- [ ] 정보처리기사 실기 개념 2강

- [ ] 자바 어드민페이지 구현  

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 자바 인강 15회 분으로 나누어서 계획 짜서 알려주세요

**Comment by sohoung** [comment]
12.09 00 ~ 03
12.10 04 ~ 07
12.13 08 ~ 11
12.14 12 ~ 15
12.15 16 ~ 19
12.16 20 ~ 23
12.17 24 ~ 7-1
12.20 7-2 ~ 8-1-03
12.21 8-1-04 ~ 8-2-02
12.22 8-2-03 ~ 8-3-01
12.23 8-3-02 ~ 9-01
12.24 9-02 ~ 9-05
12.27 9-06 ~ 12

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222591510705

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222591421426
