### ISSUE TITLE
[21-12-10] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#30]
- [ ] 정보처리기사 실기 개념 3강

- [ ] 자바 어드민페이지 구현 프로젝트  04 ~ 07

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11
