### ISSUE TITLE
[21-12-10] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#32]
- [ ] 정보처리기사 실기 개념 3강

- [ ] 스위프트 11강 원피스 현상금업그레이드(1)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260
