### ISSUE TITLE
[21-12-10] 김형민 To-do 

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#33]
- [ ] 정보처리기사 실기 개념 3강

- [ ] 딥러닝 이미지학습과 CNN project

- [ ] 딥러닝 공부 후 블로그 포스팅 후 댓글

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222592311598
