### ISSUE TITLE
[21-12-13] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#34]
- [] 정보처리기사 실기 개념 4강

- [ ] 정보처리기사 실기 문제풀이 1강

- [] 자바 어드민페이지 구현 프로젝트  04~07

- [] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 실기 문제풀이 요구사항확인 문제 풀기

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222594738568
