### ISSUE TITLE
[21-12-13] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#35]
- [ ] 정보처리기사 실기 개념 4강

- [ ] 정보처리기사 실기 문제풀이 1강

- [ ] 리엑트 2장 {00강 ~ 05강}

- [ ] 리엑트 공부한거 블로그에 포스팅 후 댓글

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222594784998
