### ISSUE TITLE
[21-12-13] 박광현 To-do 

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#36]
- [ ] 정보처리기사 실기 개념 4강

- [ ] 정보처리기사 실기 문제풀이 1강

- [ ] 스위프트 12강 애플뮤직st 음악앱 (1/2)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260/222594666125
