### ISSUE TITLE
[21-12-13] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#37]
- [ ] 정보처리기사 실기 개념 4강

- [ ] 정보처리기사 실기 문제풀이 1강

- [ ] 딥러닝 이미지학습과 CNN project (2/2)

- [ ] 딥러닝 공부한거 블로그에 포스팅 후 댓글

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222594691588
