### ISSUE TITLE
[21-12-14] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#38]
- [ ] 정보처리기사 실기 개념 5강

- [ ] 스위프트 12강 애플뮤직st 음악앱 (2/3)

- [ ] 스위프트 관련 블로그 포스팅 후 댓글

- [ ] 정보처리기사 문제풀기 <데이터 입출력>

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260
