### ISSUE TITLE
[21-12-14] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#39]
- [ ] 정보처리기사 실기 개념 5강

- [ ] 리엑트 2장 {06강 ~ 13강}

- [ ] 리엑트 관련 블로그 포스팅 후 댓글

- [ ] 정보처리기사 문제풀기 <데이터 입출력>

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222595701062
