### ISSUE TITLE
[21-12-14] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#40]
- [ ] 정보처리기사 실기 개념 5강

- [ ] 정보처리기사 문제풀기 <데이터 입출력> (5강 듣고 푸세요)

- [ ] 자바 어드민페이지 구현 프로젝트  08~11

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222595624197
