### ISSUE TITLE
[21-12-14] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#41]
- [ ] 정보처리기사 실기 개념 5강

- [ ] 정보처리기사 문제풀기 <데이터 입출력> (5강 듣고 푸세요)

- [ ] 딥러닝 텐서플로우 전이학습까지

- [ ] 딥러닝 공부한거 블로그에 포스팅 후 댓글

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222595623097
