### ISSUE TITLE
[21-12-15] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#42]
- [ ] 정보처리기사 실기 개념 6강

- [ ] 정보처리기사 문제풀이 2강

- [ ] 스위프트 12강 애플뮤직st 음악앱 (3/3)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260/222596540876 
2개임
