### ISSUE TITLE
[21-12-15] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#44]
- [ ] 정보처리기사 실기 개념 6강

- [ ] 정보처리기사 문제풀이 2강

- [ ] 자바 어드민페이지 구현 프로젝트 16 ~ 19

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222596478029
