### ISSUE TITLE
[21-12-15] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#45]
- [ ] 정보처리기사 실기 개념 6강

- [ ] 정보처리기사 문제풀이 2강

- [ ] Sequence 학습과 RNN (1/3)

- [ ] 딥러닝 공부한거 블로그에 포스팅 후 댓글

**Comment by gudals-kim** [comment]
모듈 개발로 대체
