### ISSUE TITLE
[21-12-16] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#46]
- [ ] 정보처리기사 실기 개념 7강

- [ ] 정보처리기사 통합구현 문제풀기

- [ ] 스위프트 13강 todo리스트 앱 (1/2)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글
