### ISSUE TITLE
[21-12-16] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#47]
- [ ] 정보처리기사 실기 개념 7강

- [ ] 정보처리기사 통합구현 문제풀기

- [ ] 자바 어드민페이지 프로젝트 20 ~ 23

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222597378712
