### ISSUE TITLE
[21-12-16] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#48]
- [ ] 정보처리기사 실기 개념 7강

- [ ] 정보처리기사 통합구현 문제풀기

- [ ] 리엑트 4장 {00강 ~ 03강}

- [ ] 리엑트 공부한거 블로그에 포스팅 후 댓글

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222597488979
