### ISSUE TITLE
[21-12-16] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#49]
- [ ] 정보처리기사 실기 개념 7강

- [ ] 정보처리기사 통합구현 문제풀기

- [ ] 프로토타입 모듈 완성하기

- [ ] 딥러닝 공부한거 블로그에 포스팅 후 댓글
