### ISSUE TITLE
[21-12-17] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#51]
- [ ] 정보처리기사 실기 개념 8강

- [ ] 정보처리기사 문제풀이 3강

- [ ] 자바 어드민페이지 프로젝트 24 ~ 7-1

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222599486452
