### ISSUE TITLE
[21-12-17] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#53]
- [ ] 정보처리기사 실기 개념 8강

- [ ] 정보처리기사 문제풀이 3강

- [ ] 프로토타입 모듈 완성하기

- [ ] 딥러닝 공부한거 블로그에 포스팅 후 댓글
