### ISSUE TITLE
[21-12-02] 김형민 To-Do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/everyeat#7]
금일 할 일 입니다.

- [ ] PageID-w001 웹 메인 페이지 디자인

- [ ] PageID-w002, PageID-w003, PageID-w004, PageID-w005 웹 로그인 페이지 디자인

- [ ] PageID-w006, PageID-w007 웹 고객센터 페이지 디자인

- [ ] 정보처리기사 필기 심화 8강
